stages:
 - build
 - deploy

build_images:
 stage: build
 tags:
  - docker-compose
 only:
  - master
  - develop   
 script:
  - docker-compose build


deploy_prod_app:
 stage: deploy
 tags:
  - docker-compose
  - docker-deploy
 only:
  - master 
 script:
  - docker-compose up -d