version: '3.6'
services:
  app:
    container_name: nys-app
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8085:8085"    
    environment:
      - "ASPNETCORE_URLS=http://0.0.0.0:8085"
      - "VIRTUAL_HOST=name.aska.one"
      - "LETSENCRYPT_HOST=name.aska.one"
      - "LETSENCRYPT_EMAIL=dmitry.mitichenko@gmail.com"
